/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.TransaksiController;
import control.ProdukController;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import java.awt.event.ItemEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produk;
import model.Transaksi;
import model.TransaksiDetail;

/**
 *
 * @author lenovo
 */
public class TransaksiView extends javax.swing.JFrame {

    private TransaksiController transaksiCtrl;
    private ProdukController produkCtrl;
    private ArrayList<TransaksiDetail> arrDetail;
    int jmlProdukKembali = 0;

    public TransaksiView() throws SQLException {
        initComponents();
        this.transaksiCtrl = new TransaksiController();
        this.produkCtrl = new ProdukController();
        this.arrDetail = new ArrayList<>();
        this.showComboBoxProduk();
        this.showTableKeranjang();
        this.showTableTransaksi();
    }

    public void showComboBoxProduk() throws SQLException {
        DefaultComboBoxModel dcbmP = new DefaultComboBoxModel();
        dcbmP.addElement("0 - Pilih Produk ");
        for (Produk p : this.produkCtrl.getDataproduk(null)) {
            dcbmP.addElement(p.getId_produk() + " - " + p.getNama_produk());
        }
        this.cbProduk.removeAllItems();
        this.cbProduk.setModel(dcbmP);
        tfStok.setEditable(false);
        tfHarga.setEditable(false);

        cbProduk.addItemListener((ItemEvent e) -> {
            try {
                String item = cbProduk.getSelectedItem().toString();
                int id = Integer.parseInt(item.substring(0, item.indexOf(" -")));
                if (id > 0) {
                    Produk p = new Produk();
                    p.setId_produk(id);
                    Produk prod = produkCtrl.getDataproduk(p).get(0);
                    tfHarga.setText(String.valueOf(prod.getHarga()));
                    tfStok.setText(String.valueOf(prod.getStok()));
                }
            } catch (SQLException ex) {
                Logger.getLogger(TransaksiView.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    public void showTableKeranjang() {
        DefaultTableModel dtmKeranjang = new DefaultTableModel(new String[]{"Nama Produk", "Harga ", "Qty pesan", "Total Harga"}, 0);
        dtmKeranjang.setRowCount(0);
        for (TransaksiDetail p : this.arrDetail) {
            dtmKeranjang.addRow(new String[]{p.getProduk().getNama_produk().toString(), String.valueOf(p.getProduk().getHarga()), String.valueOf(p.getQtyProduk()), p.getTotalHarga()});
        }
        this.tblKeranjang.setModel(dtmKeranjang);
    }

    public void showTableTransaksi() throws SQLException {
        DefaultTableModel dtmTransaksi = new DefaultTableModel(new String[]{"ID", "TGL MASUK ", "TGL KELUAR", "JUMLAH PRODUK DIPESAN", "JUMLAH PRODUK KEMBALI", "Total Harga"}, 0);
        dtmTransaksi.setRowCount(0);
        for (Transaksi t : this.transaksiCtrl.getTransaksi(null)) {
            dtmTransaksi.addRow(new String[]{t.getId_transaksi().toString(), t.getTgl_masuk().toString(), t.getTgl_keluar().toString(), String.valueOf(t.getJumlah_produk()), String.valueOf(t.getJml_produk_kmbli()), String.valueOf(t.getTotal())});
        }
        this.tblTransaksi.setModel(dtmTransaksi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        tfStok = new javax.swing.JTextField();
        tfJumlah = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKeranjang = new javax.swing.JTable();
        btnPesan = new javax.swing.JButton();
        btnBatalPesan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        btnDetailPesanan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfTglKeluar = new javax.swing.JTextField();
        tfTglMasuk = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnPegawai = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        cbProduk = new javax.swing.JComboBox();
        btnProduk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel1.setText("TRANSAKSI");

        jLabel2.setText("PRODUK");

        jLabel3.setText("NAMA");

        jLabel4.setText("STOK");

        jLabel5.setText("HARGA");

        jLabel6.setText("JUMLAH");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnCancel.setText("Batal");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Produk", "Harga", "stok"
            }
        ));
        jScrollPane1.setViewportView(tblKeranjang);
        if (tblKeranjang.getColumnModel().getColumnCount() > 0) {
            tblKeranjang.getColumnModel().getColumn(0).setResizable(false);
        }

        btnPesan.setText("Pesan");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        btnBatalPesan.setText("Batal");
        btnBatalPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalPesanActionPerformed(evt);
            }
        });

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblTransaksi);

        btnDetailPesanan.setText("Detail Transaksi");
        btnDetailPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailPesananActionPerformed(evt);
            }
        });

        jLabel7.setText("TGL MASUK");

        jLabel8.setText("TGL KELUAR");

        jLabel9.setText("DAFTAR TRANSAKSI");

        btnPegawai.setText("Pegawai");
        btnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegawaiActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        cbProduk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnProduk.setText("Produk");
        btnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProduk)
                        .addGap(18, 18, 18)
                        .addComponent(btnPegawai)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfTglMasuk)
                                    .addComponent(cbProduk, 0, 200, Short.MAX_VALUE)
                                    .addComponent(tfHarga))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfTglKeluar)
                                    .addComponent(tfJumlah)
                                    .addComponent(tfStok, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCancel)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTambah))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBatalPesan)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnPesan)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(394, 394, 394)
                                .addComponent(btnDetailPesanan))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduk)
                    .addComponent(btnPegawai)
                    .addComponent(btnLogout))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cbProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(tfTglMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfTglKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel)
                            .addComponent(btnTambah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatalPesan)
                    .addComponent(btnDetailPesanan)
                    .addComponent(btnPesan))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegawaiActionPerformed
        try {
            new PegawaiView().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TransaksiView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPegawaiActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.cbProduk.setSelectedIndex(0);
        this.tfStok.setText("");
        this.tfHarga.setText("");
        this.tfJumlah.setText("");
        this.tfTglKeluar.setText("");
        this.tfTglMasuk.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnBatalPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalPesanActionPerformed
        this.cbProduk.setSelectedIndex(0);
        this.tfStok.setText("");
        this.tfHarga.setText("");
        this.tfJumlah.setText("");
        this.tfTglKeluar.setText("");
        this.tfTglMasuk.setText("");
        this.arrDetail.clear();
    }//GEN-LAST:event_btnBatalPesanActionPerformed

    private void btnDetailPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailPesananActionPerformed
        int col = 0;
        int row = tblTransaksi.getSelectedRow();
        System.out.println("ROW = " + row);
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Transaksi belum dipilih, Pilih transaksi terlebih dahulu !");
        } else {

            try {
                String id = tblTransaksi.getModel().getValueAt(row, col).toString();
                System.out.println("ID = " + id);
                Transaksi t = new Transaksi();
                t.setId_transaksi(Integer.parseInt(id));
                Transaksi transaksi = this.transaksiCtrl.getTransaksi(t).get(0);
                new TransaksiDetailView(transaksi).show();

            } catch (SQLException ex) {
                Logger.getLogger(TransaksiView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDetailPesananActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String item = cbProduk.getSelectedItem().toString();
        int id = Integer.parseInt(item.substring(0, item.indexOf(" -")));
        Produk p = new Produk();
        p.setId_produk(id);
        try {
            Produk prod = produkCtrl.getDataproduk(p).get(0);
            int jumlahP = Integer.parseInt(tfJumlah.getText().toString());
            int stokProduk = Integer.parseInt(tfStok.getText().toString());
            double totalHarga = prod.getHarga() * jumlahP;
            TransaksiDetail detail = new TransaksiDetail();
            detail.setIdProduk(prod.getId_produk());
            detail.setHargaProduk(String.valueOf(prod.getHarga()));
            detail.setQtyProduk(jumlahP);
            detail.setTotalHarga(String.valueOf(totalHarga));
            detail.setProduk(prod);
            this.arrDetail.add(detail);
            this.showTableKeranjang();

            // jmlprodukkembali
            jmlProdukKembali += (stokProduk - jumlahP);
        } catch (SQLException ex) {
            Logger.getLogger(TransaksiView.class.getName()).log(Level.SEVERE, null, ex);
        }

        cbProduk.setSelectedIndex(0);
        tfStok.setText("");
        tfHarga.setText("");
        tfJumlah.setText("");
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukActionPerformed
        try {
            new ProdukView().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TransaksiView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProdukActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        try {
            new LoginView().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TransaksiView.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();


    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed

        try {
            int totalPesan = arrDetail.size();
            if (totalPesan < 1) {
                JOptionPane.showMessageDialog(null, "Produk belum ditambahkan, Pilih dan tambahkan produk terlebih dahulu !");
            } else {

                try {
                    Transaksi transaksi = new Transaksi();
                    transaksi.setTgl_masuk(new SimpleDateFormat("dd/MM/yyyy").parse(this.tfTglMasuk.getText()));
                    transaksi.setTgl_keluar(new SimpleDateFormat("dd/MM/yyyy").parse(this.tfTglKeluar.getText()));
                    transaksi.setTransaksiDetails(arrDetail);
                    transaksi.setJml_produk_kmbli(jmlProdukKembali);
                    this.transaksiCtrl.insertTransaksi(transaksi);
                    this.showTableTransaksi();
                } catch (SQLException ex) {
                    Logger.getLogger(TransaksiView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(TransaksiView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TransaksiView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TransaksiView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalPesan;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDetailPesanan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPegawai;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnProduk;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox cbProduk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblKeranjang;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfStok;
    private javax.swing.JTextField tfTglKeluar;
    private javax.swing.JTextField tfTglMasuk;
    // End of variables declaration//GEN-END:variables
}
